# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Wait 100 milliseconds for starship to check files under the current directory.
scan_timeout = 100

# Timeout for commands executed by starship (in milliseconds).
command_timeout = 3000

# Replace the 'â¯' symbol in the prompt with 'âœ'
[character] # The name of the module we are configuring is 'character'
success_symbol = '[âœ](bold green)' # The 'success_symbol' segment is being set to 'âœ' with the color 'bold green'

# Force display aws config
[aws]
force_display = true

[kubernetes]
# disabled k8s for now.
disabled = true

[hostname]
ssh_only = true
trim_at = ''

[package]
format = 'via [ğŸ $version](208 bold) '

[terraform]
format = '[ğŸğŸ’¨ $version]($style) '

